version: '3'

services:
    web-app:
        # Use the image built from the Dockerfile in the current directory
        image: node:latest
        # Read environment variables from the .env file
        env_file:
            - .env
        # Specify the working directory inside the container
        working_dir: /app
        # Mount the current directory into the container for live code editing
        volumes:
            - .:/app
            - ../shared:/app/shared
        # Expose the development server port (if needed)
        ports:
            - '5173:5173'
        # Install and run the development server using Yarn
        command:
            - sh
            - -c
            - |
                cd /app/shared
                yarn install
                yarn build
                yarn link
                cd /app
                yarn install
                yarn link '@sanctuaryteam/shared'
                yarn dev --host
